// Created by iWeb 3.0.4 local-build-20140605

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-5,5,10,184),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_8.png'},{rect:new IWRect(-5,-5,10,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_9.png'},{rect:new IWRect(5,-5,249,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_10.png'},{rect:new IWRect(254,-5,10,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_11.png'},{rect:new IWRect(254,5,10,184),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_12.png'},{rect:new IWRect(254,189,10,11),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_13.png'},{rect:new IWRect(5,189,249,11),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_14.png'},{rect:new IWRect(-5,189,10,11),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_15.png'}],new IWSize(259,194)),stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,210),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_1.png'},{rect:new IWRect(5,-5,385,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_2.png'},{rect:new IWRect(390,-5,10,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_3.png'},{rect:new IWRect(390,5,10,210),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_4.png'},{rect:new IWRect(390,215,10,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_5.png'},{rect:new IWRect(5,215,385,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_6.png'},{rect:new IWRect(-5,215,10,10),url:'4_Java-paivitys,_Finder_ja_reset-ruutu_files/stroke_7.png'}],new IWSize(395,220))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('4_Java-paivitys,_Finder_ja_reset-ruutu_files/4_Java-paivitys,_Finder_ja_reset-ruutuMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();fixupIECSS3Opacity('id8');applyEffects()}
function onPageUnload()
{Widget.onunload();}
